#!/usr/bin/env python3
"""seb_toggle.py - scan, classify, and toggle restrictions in a Safe Exam Browser .seb config.

Implements plan.md sections 3-7:
  sec 3  input handling + two refusal paths
  sec 4  value-semantics layer (polarity model)
  sec 5  scan pass, six-state classification, three-state DEFAULT column
  sec 6  toggle UX
  sec 7  output write + 5 self-verification assertions

Registry authority: seb_registry.json (generated by build_registry.py from Keys.cs).
Never edit the input in place. Never write binary plist output.
"""

import argparse
import base64
import plistlib
import sys
from pathlib import Path

if getattr(sys, "frozen", False):
    # PyInstaller unpacks bundled data into _MEIPASS; the CLI script is not on disk there.
    REGISTRY_PATH = Path(getattr(sys, "_MEIPASS", Path(sys.executable).parent)) / "seb_registry.json"
else:
    REGISTRY_PATH = Path(__file__).with_name("seb_registry.json")

# sec 3.1 - SEB binary container magic (DataFormats/BinaryParser.cs + GZipCompressor.cs)
SEB_MAGIC = {b"plnd", b"pswd", b"pwcc", b"pkhs", b"phsk"}

# sec 3.2 - key whose presence means the config is encrypted end-to-end
ENCRYPTION_KEY = "useAsymmetricOnlyEncryption"

# sec 4.2 - non-boolean value models. Encodings derived from the mapper bodies in
# ...ConfigurationData.DataMapping/*.cs and the enum declarations in Configuration/*.cs.
# 'to' maps a symbolic choice to the value written to the plist.
ENUM_SPACES = {
    # wire key sebConfigPurpose -> ConfigurationFileDataMapper.MapConfigurationMode
    #   ConfigurationMode = ((num != 1) ? Exam : ConfigureClient)
    "sebConfigPurpose": {
        "choices": ["Exam", "ConfigureClient"],
        "to": {"Exam": 0, "ConfigureClient": 1},
        "from": {0: "Exam", 1: "ConfigureClient"},
        "controls": "ConfigurationMode  [(num != 1) ? Exam : ConfigureClient]",
    },
    # wire key sebMode -> ConfigurationFileDataMapper.MapSessionMode
    #   SessionMode = ((num == 1) ? Server : Normal)
    "sebMode": {
        "choices": ["Normal", "Server"],
        "to": {"Normal": 0, "Server": 1},
        "from": {0: "Normal", 1: "Server"},
        "controls": "SebMode  [(num == 1) ? Server : Normal]",
    },
    # wire key clipboardPolicy -> SecurityDataMapper.MapClipboardPolicy
    #   switch: 1 => Block, 0 => Allow, _ => Isolated
    "clipboardPolicy": {
        "choices": ["Allow", "Block", "Isolated"],
        "to": {"Allow": 0, "Block": 1, "Isolated": 2},
        "from": {0: "Allow", 1: "Block", 2: "Isolated"},
        "controls": "Security.ClipboardPolicy  [switch 1/0/_]",
    },
    # wire key allowVirtualMachine -> SecurityDataMapper.MapVirtualMachinePolicy
    #   VirtualMachinePolicy = ((!flag) ? Deny : Allow)   <- inverted
    "allowVirtualMachine": {
        "choices": ["Allow", "Deny"],
        "to": {"Allow": True, "Deny": False},
        "from": {True: "Allow", False: "Deny"},
        "controls": "Security.VirtualMachinePolicy  [(!flag) ? Deny : Allow]",
    },
    # wire key browserViewMode -> BrowserDataMapper.MapMainWindowMode
    #   FullScreenMode = (num == 1).  There is no third state: any num != 1 is windowed.
    "browserViewMode": {
        "choices": ["Windowed", "FullScreen"],
        "to": {"Windowed": 0, "FullScreen": 1},
        "from": {0: "Windowed", 1: "FullScreen"},
        "controls": "Browser.MainWindow.FullScreenMode  [num == 1]",
    },
    # wire key touchOptimized -> UserInterfaceDataMapper.MapUserInterfaceMode
    #   Mode = (flag ? Mobile : Desktop)
    # NOTE: this is an inversion of the wire boolean (True => Mobile), but it is NOT in
    # the registry's inverted set, because `inverted` there means C#-`!flag`, which this
    # mapper expresses as a ternary instead. It is a bool-valued key; see BOOL_ENUM_KEYS.
    "touchOptimized": {
        "choices": ["Desktop", "Mobile"],
        "to": {"Desktop": False, "Mobile": True},
        "from": {False: "Desktop", True: "Mobile"},
        "controls": "UserInterface.Mode  [(flag) ? Mobile : Desktop]",
    },
}

# Keys whose wire value is an INT that the mapper collapses to a boolean. Offered as a
# toggle only against the enum space above, never as a raw 0/1 int.
INT_BOOL_KEYS = {"browserViewMode"}

# ------------------------------------------------------------------ relaxation profile
# A curated set, NOT a blanket "set every boolean to True". Several keys are MORE
# permissive when False (killExplorerShell, URLFilterEnable, audioMute) and several
# are not restrictions at all (touchOptimized is an enum, audioSetVolumeLevel is a
# level). Flipping those would tighten the config instead of opening it. Every entry
# below is justified by the key's own name; keys whose direction is uncertain are
# deliberately left out rather than guessed.
UNLOCK_BOOL = {
    # screen capture and sharing
    "enablePrintScreen": True,
    "allowScreenSharing": True,
    "showApplicationLogButton": True,
    # keyboard and OS
    "enableAltTab": True, "enableAltEsc": True, "enableAltF4": True,
    "enableCtrlEsc": True, "enableEsc": True, "enableStartMenu": True,
    "enableMiddleMouse": True, "enableRightMouse": True,
    "enableF1": True, "enableF2": True, "enableF3": True, "enableF4": True,
    "enableF5": True, "enableF6": True, "enableF7": True, "enableF8": True,
    "enableF9": True, "enableF10": True, "enableF11": True, "enableF12": True,
    "enableWindowsUpdate": True,
    # OS actions from inside SEB
    "insideSebEnableChangeAPassword": True, "insideSebEnableEaseOfAccess": True,
    "insideSebEnableLockThisComputer": True, "insideSebEnableLogOff": True,
    "insideSebEnableNetworkConnectionSelector": True, "insideSebEnableShutDown": True,
    "insideSebEnableStartTaskManager": True, "insideSebEnableSwitchUser": True,
    "insideSebEnableVmWareClientShade": True,
    # browser features
    "allowBrowsingBackForward": True, "browserWindowAllowAddressBar": True,
    "newBrowserWindowAllowAddressBar": True, "enableBrowserWindowToolbar": True,
    "downloadPDFFiles": True, "allowPDFReaderToolbar": True, "allowSpellCheck": True,
    "allowDeveloperConsole": True, "allowWlan": True,
    "allowCustomDownUploadLocation": True, "enableZoomPage": True, "allowFind": True,
    "allowApplicationLog": True, "newBrowserWindowShowReloadWarning": True,
    # desktop lockdown - these are switched OFF, so False is the permissive value
    "createNewDesktop": False,
    "killExplorerShell": False,
    "removeBrowserProfile": False,
    "newBrowserWindowByLinkBlockForeign": False,
    # URL filtering - switched OFF
    "URLFilterEnable": False,
    "URLFilterEnableContentFilter": False,
    # audio - unmuted
    "audioMute": False,
}

UNLOCK_ENUM = {"allowVirtualMachine": "Allow", "clipboardPolicy": "Allow"}
UNLOCK_LISTS = ("prohibitedProcesses", "permittedProcesses")


def build_unlock(data):
    """Return {key: permissive_value} for every key this profile can move."""
    intended = {}
    for k, v in UNLOCK_BOOL.items():
        if isinstance(data.get(k), bool) and data[k] != v:
            intended[k] = v
    for k, label in UNLOCK_ENUM.items():
        space = ENUM_SPACES.get(k)
        if k in data and space and label in space["to"]:
            v = space["to"][label]
            if data[k] != v:
                intended[k] = v
    for k in UNLOCK_LISTS:
        cur = data.get(k)
        if isinstance(cur, list) and cur:
            new = []
            off = 0
            for e in cur:
                if isinstance(e, dict) and e.get("active"):
                    e = dict(e)
                    e["active"] = False
                    off += 1
                new.append(e)
            if off:
                intended[k] = new
    return intended

# Keys that are structurally non-boolean but carry no discrete enum space.
OPAQUE_KEYS = {
    "hashedAdminPassword", "hashedQuitPassword", "examKeySalt", "browserExamKey",
    "configKeySalt", "prohibitedProcesses", "permittedProcesses", "proxies",
    "allowedDisplaysMaxNumber", "startURL", "sebServerURL", "originatorVersion",
}


# --------------------------------------------------------------------------- ui
import os as _os
import re as _re

_ANSI_RE = _re.compile(r"\x1b\[[0-9;]*m")


def _forced():
    return bool(_os.environ.get("SEB_FORCE_COLOR"))


def _ansi_ok():
    if _os.environ.get("NO_COLOR") and not _forced():
        return False
    if not _forced() and not sys.stdout.isatty():
        return False
    if _os.name == "nt":
        try:
            import ctypes
            _k = ctypes.windll.kernel32
            _k.SetConsoleMode(_k.GetStdHandle(-11), 7)
        except Exception:
            return False
    return True


RICH = _ansi_ok()


def _uni_ok():
    if not RICH:
        return False
    return "utf" in (getattr(sys.stdout, "encoding", "") or "").lower()


UNI = _uni_ok()


def set_rich(v):
    global RICH, UNI
    RICH = bool(v)
    UNI = _uni_ok()


def _w(code, s):
    return "\033[%sm%s\033[0m" % (code, s) if RICH else s


def bold(s):
    return _w("1", s)


def dim(s):
    return _w("2", s)


def red(s):
    return _w("31", s)


def green(s):
    return _w("32", s)


def yellow(s):
    return _w("33", s)


def blue(s):
    return _w("34", s)


def magenta(s):
    return _w("35", s)


def cyan(s):
    return _w("36", s)


def grey(s):
    return _w("90", s)


_STATUS_FN = {
    "PERMISSIVE": green,
    "RESTRICTION": red,
    "RESTRICTION SEB default": yellow,
    "RESTRICTION author-imposed": lambda s: _w("1;31", s),
    "MODE-SELECTOR": cyan,
    "IGNORED-BY-3.10.2": grey,
    "ABSENT-DEFAULTED": blue,
}


def st(s):
    return _STATUS_FN.get(s, lambda x: x)(s)


def _eff_color(v):
    if v in ("permits", "Allow", "Normal"):
        return green(v)
    if v in ("restricts", "Deny", "Block", "Server", "FullScreen", "Mobile"):
        return red(v)
    return cyan(v)


def _def_color(v):
    if v == "author-imposed":
        return magenta(v)
    if v == "n/a":
        return grey(v)
    return yellow(v)


def _strip(s):
    return _ANSI_RE.sub("", s)


def _ljust(s, w):
    d = w - len(s)
    return s + " " * d if d > 0 else s


def _pad(s, w):
    d = w - len(_strip(s))
    return s + " " * d if d > 0 else s


if UNI:
    TL, TR, BL, BR, H, V = "\u256d", "\u256e", "\u2570", "\u256f", "\u2500", "\u2502"
    LT, RT = "\u251c", "\u2524"
else:
    TL = TR = BL = BR = LT = RT = "+"
    H, V = "-", "|"

WIDTH = 78


def _box(lines, title=None, color=None, width=None):
    color = color or cyan
    width = width or WIDTH
    out = [color(TL + H * (width - 2) + TR)]
    if title:
        out.append(color(V) + " " + bold(_pad(title, width - 4)) + " " + color(V))
        out.append(color(LT + H * (width - 2) + RT))
    for ln in lines:
        out.append(color(V) + " " + _pad(_clip(ln, width - 4), width - 4) + " " + color(V))
    out.append(color(BL + H * (width - 2) + BR))
    return "\n".join(out)


def _clip(s, w):
    if len(_strip(s)) <= w:
        return s
    return _strip(s)[:w - 3] + "..."


def _fmt_bytes(n):
    if n is None:
        return "-"
    if n < 1024:
        return "%d B" % n
    if n < 1048576:
        return "%.1f KB" % (n / 1024.0)
    return "%.1f MB" % (n / 1048576.0)


def _bar(n, total, width=30):
    if total <= 0:
        return ""
    filled = int(round(width * n / float(total)))
    ch, em = ("\u2588", "\u2591") if UNI else ("#", ".")
    return ch * filled + em * (width - filled)


def print_report_rich(data, rows, absent, reg, size, path):
    c = counts(rows, absent)
    ai = [r for r in rows if r["default"] == "author-imposed"]
    sd = [r for r in rows if r["default"] == "SEB default"]
    na = [r for r in rows if r["status"] in ("PERMISSIVE", "RESTRICTION") and r["default"] == "n/a"]
    restricting = c["RESTRICTION"] + c["RESTRICTION SEB default"] + c["RESTRICTION author-imposed"]
    permitting = c["PERMISSIVE"]
    modes = c["MODE-SELECTOR"]
    ignored = c["IGNORED-BY-3.10.2"]
    defaulted = c["ABSENT-DEFAULTED"]

    print()
    print(_box([bold("S E B   C O N F I G   S C A N"),
                dim("Safe Exam Browser 3.10.2  -  restriction surface analyzer")]))
    print()
    meta = [("file", str(path)),
            ("originatorVersion", str(data.get("originatorVersion", "(absent)"))),
            ("size", _fmt_bytes(size)),
            ("keys in file", str(len(rows))),
            ("registry keys", str(len(reg.keys))),
            ("categories", str(len(reg.categories)))]
    mw = max(len(k) for k, _ in meta)
    for k, v in meta:
        print("  " + dim(_ljust(k, mw)) + "   " + v)
    print()

    dl = [bold("author-imposed") + "   " + magenta("%-3d" % len(ai)) + "  " + dim("real author edits")]
    for r in ai:
        dl.append("   " + yellow(r["key"]) + " = " + str(r["raw"]) + "  " + dim(r["prop"] or ""))
    dl.append(bold("SEB default") + "      " + yellow("%-3d" % len(sd)) + "  " + dim("SEB's own defaults, NOT edits"))
    dl.append(bold("default n/a") + "      " + grey("%-3d" % len(na)) + "  " + dim("no joinable code default"))
    print(_box(dl, title="DEFAULT AXIS  -  direction-independent"))
    print()

    total = max(1, len(rows))
    print(_box([green("restricting") + "    " + green("%-3d" % restricting) + "  " + red(_bar(restricting, total)),
                yellow("permitting") + "     " + yellow("%-3d" % permitting) + "  " + yellow(_bar(permitting, total)),
                cyan("mode-selector") + "  " + cyan("%-3d" % modes) + "  " + cyan(_bar(modes, total))],
               title="DIRECTION AXIS  -  raw value, direct polarity"))
    print()

    print(_box([green("recognized") + "     " + green("%-3d" % (len(rows) - ignored)) + "  " + dim("read by 3.10.2"),
                grey("ignored") + "        " + grey("%-3d" % ignored) + "  " + dim("macOS / SEB 2.x legacy"),
                blue("absent") + "         " + blue("%-3d" % defaulted) + "  " + dim("in registry, not in file")],
               title="RECOGNITION"))
    print()

    if check_encryption(data):
        print(_box([red("!! " + str(ENCRYPTION_KEY) + " = True"), "",
                    "This config declares encryption. The local override caveat",
                    "in plan.md sec 7 DOES NOT APPLY. Toggling it here will not",
                    "take effect client-side."], title="WARNING", color=red))
        print()

    if reg.collisions:
        cl = ["one wire value, two Keys.cs consts:"]
        for wv, consts in sorted(reg.collisions.items()):
            cl.append("   " + yellow(wv) + "  <- " + ", ".join(consts))
        cl.append(dim("A report that reads key names alone produces wrong findings."))
        print(_box(cl, title="WIRE-VALUE COLLISIONS", color=magenta))
        print()

    by_cat = {}
    for r in rows:
        by_cat.setdefault(r["category"], []).append(r)
    hdr = ("   " + _pad(dim("STATUS"), 26) + " " + _pad(dim("KEY"), 32) + " "
           + _pad(dim("FILE"), 9) + " " + _pad(dim("EFFECTIVE"), 14) + " "
           + _pad(dim("DEFAULT"), 16) + " " + dim("CONTROLS"))
    for cat in sorted(by_cat):
        print("  " + cyan(">") + " " + bold(cat) + "  " + dim("(%d)" % len(by_cat[cat])))
        print(hdr)
        for r in by_cat[cat]:
            flag = dim(" [inv]") if r["inverted"] else ""
            print("   " + _pad(st(r["status"]), 26) + " " + _pad(bold(r["key"]), 32) + " "
                  + _pad(fmt_raw(r["raw"]), 9) + " " + _pad(_eff_color(r["effective"]), 14) + " "
                  + _pad(_def_color(r["default"]), 16) + " "
                  + (r["prop"] or dim("(unmapped)")) + flag)
        print()

    if ignored:
        print("  " + grey("IGNORED-BY-3.10.2") + "  " + dim("macOS / SEB 2.x legacy, not read by 3.10.2"))
        for r in rows:
            if r["status"] == "IGNORED-BY-3.10.2":
                print("   " + grey(_ljust(r["key"], 44)) + " " + grey(fmt_raw(r["raw"])))
        print()
    if absent:
        print("  " + blue("ABSENT-DEFAULTED") + "  " + dim("in registry, not in file; effective = CLR false"))
        for r in absent:
            print("   " + blue(_ljust(r["key"], 44)) + " " + _pad(r["prop"] or dim("(unmapped)"), 34)
                  + " " + dim("default=" + str(r["default"])))
        print()


def print_menu_rich(entries):
    print()
    print(_box([bold("TOGGLE MENU"),
                dim("boolean keys present in this file, grouped by registry category")]))
    last = None
    for i, r in enumerate(entries, 1):
        if r["category"] != last:
            print()
            print("  " + cyan(">") + " " + bold(r["category"]))
            last = r["category"]
        cur = green("permits") if r["raw"] else red("restricts")
        val = green("True ") if r["raw"] else red("False")
        print("   " + cyan("%3d" % i) + "  " + bold(_ljust(r["key"], 36)) + " "
              + val + "  " + cur + "  " + dim((r["prop"] or "")[:38]))
    print()
    print("  " + dim("Enter:") + " 3 " + dim("|") + " 3,7,12 " + dim("|") + " 12-18 "
          + dim("|") + " all " + dim("|") + " none " + dim("|") + " " + bold("unlock")
          + dim(" | done"))
    print("  " + dim("sec 4.1: raw value, direct polarity. True permits, False restricts. Toggling flips it."))
    print()


def print_preview_rich(intended, src):
    lines = []
    for k, v in sorted(intended.items()):
        if k in src:
            lines.append(yellow("~") + " " + bold(_ljust(k, 36)) + " " + dim(fmt_raw(src[k]))
                         + " " + dim("->") + " " + green(fmt_raw(v)))
        else:
            lines.append(yellow("+") + " " + bold(_ljust(k, 36)) + " " + dim("(absent)")
                         + " " + dim("->") + " " + yellow(fmt_raw(v)) + "  " + yellow("[ADDITION]"))
    print()
    print(_box(lines or [dim("(no changes)")], title="PREVIEW DIFF", color=yellow))
    added = [k for k in intended if k not in src]
    if added:
        print("  " + yellow("additions:") + " " + ", ".join(added) + "  "
              + dim("<- these change the config's identity"))


def _diff_rich(a_path, b_path, diffs, reg):
    print()
    print(_box([bold(_os.path.basename(str(a_path))) + "  " + dim("vs") + "  "
                + bold(_os.path.basename(str(b_path))),
                "", dim(str(a_path)), dim(str(b_path))]))
    n = len(diffs)
    print("  " + dim("differing keys:") + " " + (green(str(n)) if n == 0 else red(str(n))))
    for k, va, vb in diffs:
        prop = reg.methods.get(reg.dispatch.get(k, ""), {}).get("prop", "(unmapped)")
        print("    " + yellow("~") + " " + bold(_ljust(k, 34)) + " " + red(fmt_raw(va)[:28])
              + " " + dim("->") + " " + green(fmt_raw(vb)[:28]) + "  " + dim(prop))
    print()


def print_ignored_rich(ign):
    print()
    print(_box([bold("IGNORED-BY-3.10.2"),
                dim("macOS / SEB 2.x legacy - not read by 3.10.2"),
                dim("%d keys" % len(ign))]))
    print()
    for r in ign:
        print("   " + grey(_ljust(r["key"], 44)) + " " + grey(fmt_raw(r["raw"])))
    print()


def _write_report_rich(out_path, stats):
    sb = stats["src_bytes"] or 0
    lines = [dim("bytes") + "    " + str(sb) + " -> " + str(stats["out_bytes"])
             + "  " + dim("(%+d)" % (stats["out_bytes"] - sb)),
             dim("keys") + "     " + str(stats["src_keys"]) + " -> " + str(stats["out_keys"])
             + "  " + dim("(%+d)" % (stats["out_keys"] - stats["src_keys"]))]
    if stats["added"]:
        lines.append(yellow("added") + "    " + str(stats["added"]))
    print()
    print(_box([bold(str(out_path))] + lines, title="WRITE", color=green))


class Refused(Exception):
    """Input refused before any write. Never produces output."""


# --------------------------------------------------------------------------- registry

class Registry:
    def __init__(self, path):
        import json
        if not path.exists():
            raise SystemExit("registry missing: %s - run build_registry.py first" % path)
        raw = json.loads(path.read_text(encoding="utf-8"))
        self.keys = raw["keys"]              # wire key -> Keys.cs category path
        self.dispatch = raw["dispatch"]      # wire key -> Map* method
        self.methods = raw["methods"]        # Map* method -> {file, prop, expr, inverted}
        self.defaults = raw["defaults"]      # property path -> default literal
        self.categories = raw["categories"]  # category path -> [wire keys]
        self.collisions = raw.get("const_collisions", {})
        self.key_cat = {}
        for cat, ks in self.categories.items():
            for k in ks:
                self.key_cat.setdefault(k, cat)

    def mapper(self, key):
        return self.methods.get(self.dispatch.get(key, ""))

    def default_literal(self, key):
        m = self.mapper(key)
        return self.defaults.get(m["prop"]) if m else None

    def category(self, key):
        return self.key_cat.get(key, "Keys.Unknown")

    def is_known(self, key):
        return key in self.keys


def parse_default_bool(literal):
    """sec 2.4 - Literals in LoadDefaultSettings() are already PROPERTY-space values.

    Compare propval against this directly. Never invert the default.
    Returns True/False, or None when the literal is absent or non-boolean.
    """
    if literal is None:
        return None
    s = literal.strip()
    if s.startswith('"') and s.endswith('"'):
        s = s[1:-1]
    if s == "true":
        return True
    if s == "false":
        return False
    return None


# --------------------------------------------------------------------------- sec 3

def detect_and_load(path):
    """sec 3.1 - format detection, first match wins. Raises Refused with a clean message."""
    p = Path(path)
    if not p.exists():
        raise Refused("no such file: %s" % p)
    blob = p.read_bytes()
    head = blob[:4]

    if head in SEB_MAGIC:
        raise Refused(
            "SEB binary container detected (prefix %r, %d bytes).\n"
            "  This is the encrypted/compressed container handled by\n"
            "  DataFormats/BinaryParser.cs + GZipCompressor.cs, not a plist.\n"
            "  Out of scope - refusing." % (head.decode("ascii", "replace"), len(blob))
        )

    try:
        with p.open("rb") as fh:
            data = plistlib.load(fh, fmt=None)
    except Exception as exc:
        raise Refused(
            "not a plist and not a recognized SEB container.\n"
            "  leading bytes (hex): %s\n"
            "  parser error: %s: %s" % (blob[:16].hex(" "), type(exc).__name__, exc)
        )

    if not isinstance(data, dict):
        raise Refused("plist root is %s, expected a dictionary" % type(data).__name__)
    return data, len(blob)


def check_encryption(data):
    """sec 3.2 - a key read, not a format inspection."""
    return data.get(ENCRYPTION_KEY) is True


# --------------------------------------------------------------------------- sec 4 / 5

def effective_propval(raw, inverted):
    """sec 4.1 - config flag -> property value. Toggle logic never needs this;
    it exists so the DEFAULT column can be compared like-for-like."""
    if isinstance(raw, bool):
        return (not raw) if inverted else raw
    return raw


def classify(key, reg):
    """sec 5.1 - returns a row dict for one key present in the file."""
    cat = reg.category(key)
    m = reg.mapper(key)
    raw = None  # filled by caller
    row = {
        "key": key,
        "category": cat,
        "known": reg.is_known(key),
        "mapper": reg.dispatch.get(key),
        "prop": m["prop"] if m else None,
        "inverted": bool(m["inverted"]) if m else False,
        "default_literal": reg.default_literal(key),
    }
    return row


def classify_value(row, raw, reg):
    """sec 5.1 - assign STATUS / EFFECTIVE / DEFAULT given the raw value."""
    row["raw"] = raw
    dv = parse_default_bool(row["default_literal"])
    row["default_bool"] = dv

    if not row["known"]:
        row["status"] = "IGNORED-BY-3.10.2"
        row["effective"] = "n/a"
        row["default"] = "n/a"
        return row

    if isinstance(raw, bool):
        # sec 5.2 - a bool-valued enum key renders its semantic label; the raw
        # bool is the wire form, not the meaning. Non-enum bools stay permits/restricts.
        space = ENUM_SPACES.get(row["key"])
        if space and raw in space["from"]:
            row["effective"] = space["from"][raw]
        else:
            row["effective"] = "permits" if raw else "restricts"
        if dv is None:
            row["default"] = "n/a"
            # absence of a default is not evidence of an edit (sec 5.1)
            row["status"] = "PERMISSIVE" if raw else "RESTRICTION"
        else:
            propval = effective_propval(raw, row["inverted"])
            if propval == dv:
                row["default"] = "SEB default"
                row["status"] = "PERMISSIVE" if raw else "RESTRICTION SEB default"
            else:
                row["default"] = "author-imposed"
                row["status"] = "PERMISSIVE" if raw else "RESTRICTION author-imposed"
        return row

    row["status"] = "MODE-SELECTOR"
    space = ENUM_SPACES.get(row["key"])
    if space:
        row["effective"] = space["from"].get(raw, "unknown(%r)" % (raw,))
    elif isinstance(raw, list):
        row["effective"] = "list[%d]" % len(raw)
    elif isinstance(raw, dict):
        row["effective"] = "dict[%d]" % len(raw)
    elif isinstance(raw, bytes):
        row["effective"] = "base64:" + base64.b64encode(raw).decode()[:16] + "..."
    else:
        row["effective"] = repr(raw)[:28]
    row["default"] = "n/a"
    return row


def scan(data, reg):
    """sec 5 - the full scan pass over one config."""
    rows = []
    for key in sorted(data):
        row = classify(key, reg)
        classify_value(row, data[key], reg)
        rows.append(row)

    absent = []
    for key in sorted(reg.keys):
        if key not in data:
            m = reg.mapper(key)
            absent.append({
                "key": key, "category": reg.category(key), "known": True,
                "mapper": reg.dispatch.get(key),
                "prop": m["prop"] if m else None,
                "inverted": bool(m["inverted"]) if m else False,
                "default_literal": reg.default_literal(key),
                "status": "ABSENT-DEFAULTED",
                "raw": None,
                "effective": "CLR false (constructor sets nothing)",
                "default": reg.default_literal(key) or "n/a",
            })
    return rows, absent


def counts(rows, absent):
    c = {
        "RESTRICTION author-imposed": 0, "RESTRICTION SEB default": 0,
        "RESTRICTION": 0, "PERMISSIVE": 0, "MODE-SELECTOR": 0,
        "IGNORED-BY-3.10.2": 0, "ABSENT-DEFAULTED": len(absent),
    }
    for r in rows:
        c[r["status"]] = c.get(r["status"], 0) + 1
    return c


# --------------------------------------------------------------------------- rendering

def fmt_raw(v):
    if isinstance(v, bytes):
        return "base64:%s..." % base64.b64encode(v).decode()[:16]
    if isinstance(v, list):
        return "[%d]" % len(v)
    if isinstance(v, dict):
        return "{%d}" % len(v)
    return repr(v)


def print_report(data, rows, absent, reg, size, path):
    """sec 5.3 - summary header. The two restriction counts print separately,
    author-imposed leads."""
    if RICH:
        return print_report_rich(data, rows, absent, reg, size, path)
    c = counts(rows, absent)
    print("=" * 100)
    print("SEB CONFIG SCAN")
    print("=" * 100)
    print("  file              : %s" % path)
    print("  originatorVersion : %s" % data.get("originatorVersion", "(absent)"))
    print("  bytes             : %d" % size)
    print("  keys in file      : %d" % len(rows))
    print("  registry keys     : %d" % len(reg.keys))
    print("  categories        : %d" % len(reg.categories))
    print("-" * 100)
    ai = [r for r in rows if r["default"] == "author-imposed"]
    sd = [r for r in rows if r["default"] == "SEB default"]
    na = [r for r in rows if r["status"] in ("PERMISSIVE", "RESTRICTION")
          and r["default"] == "n/a"]
    print("  DEFAULT AXIS  (sec 5.1 - direction-independent)")
    print("    author-imposed          : %-3d  <- real author edits" % len(ai))
    for r in ai:
        print("       %-36s %s   %s" % (r["key"], r["raw"], r["prop"]))
    print("    SEB default             : %-3d  <- SEB's own defaults, NOT edits" % len(sd))
    print("    default n/a             : %-3d  <- no joinable code default" % len(na))
    print("  DIRECTION AXIS  (sec 5.2 - raw value, direct polarity)")
    print("    restricting             : %-3d" % (c["RESTRICTION"] + c["RESTRICTION SEB default"]
                                                  + c["RESTRICTION author-imposed"]))
    print("    permitting              : %-3d" % c["PERMISSIVE"])
    print("    mode-selector           : %-3d" % c["MODE-SELECTOR"])
    print("  RECOGNITION")
    print("    ignored by 3.10.2       : %-3d" % c["IGNORED-BY-3.10.2"])
    print("    absent / defaulted      : %-3d" % c["ABSENT-DEFAULTED"])
    if check_encryption(data):
        print("-" * 100)
        print("  !! %s = True" % ENCRYPTION_KEY)
        print("     This config declares encryption. The local override caveat in plan.md sec 7")
        print("     DOES NOT APPLY. Toppling it here will not take effect client-side.")
    if reg.collisions:
        print("-" * 100)
        print("  wire-value collisions (one wire value, two Keys.cs consts):")
        for wv, consts in sorted(reg.collisions.items()):
            print("     %-22s <- %s" % (wv, ", ".join(consts)))
        print("     A report that reads key names alone produces wrong findings.")
    print("=" * 100)

    by_cat = {}
    for r in rows:
        by_cat.setdefault(r["category"], []).append(r)

    for cat in sorted(by_cat):
        print("\n## %s" % cat)
        print("   %-26s %-30s %-10s %-14s %-14s %s" % ("STATUS", "KEY", "FILE", "EFFECTIVE", "DEFAULT", "CONTROLS"))
        for r in by_cat[cat]:
            flag = " [inverted]" if r["inverted"] else ""
            print("   %-26s %-30s %-10s %-14s %-14s %s%s" % (
                r["status"], "%s = %s" % (r["key"], fmt_raw(r["raw"])),
                fmt_raw(r["raw"]), r["effective"], r["default"],
                r["prop"] or "(unmapped)", flag))

    ignored = [r for r in rows if r["status"] == "IGNORED-BY-3.10.2"]
    if ignored:
        print("\n## IGNORED-BY-3.10.2  (macOS / SEB 2.x legacy, not read by 3.10.2)")
        for r in ignored:
            print("   %-44s %s" % (r["key"], fmt_raw(r["raw"])))

    if absent:
        print("\n## ABSENT-DEFAULTED  (in registry, not in file; effective = CLR false)")
        for r in absent:
            print("   %-44s %-34s default=%s" % (r["key"], r["prop"] or "(unmapped)", r["default"]))
    print()


# --------------------------------------------------------------------------- sec 6

def build_menu(rows, reg, category=None):
    """Toggleable = present in file AND recognized AND boolean."""
    entries = [r for r in rows if r["known"] and isinstance(r["raw"], bool)]
    if category:
        entries = [r for r in entries if r["category"] == category]
    entries.sort(key=lambda r: (r["category"], r["key"]))
    return entries


def print_menu(entries):
    if RICH:
        return print_menu_rich(entries)
    print("TOGGLE MENU  (grouped by registry category)")
    print("-" * 100)
    last = None
    for i, r in enumerate(entries, 1):
        if r["category"] != last:
            print("\n  [%s]" % r["category"])
            last = r["category"]
        print("   %3d  %-38s %-6s %-10s %-16s %s" % (
            i, r["key"], str(r["raw"]), "permits" if r["raw"] else "restricts",
            r["default"], (r["prop"] or "")[:34]))
    print()
    print("  Enter: 3 | 3,7,12 | 12-18 | all | none | unlock | done")
    print("  Toggling flips a boolean to the opposite state (sec 4.1: raw value, direct polarity).")


def parse_selection(text, n):
    text = text.strip().lower()
    if text in ("done", ""):
        return []
    if text == "all":
        return list(range(1, n + 1))
    if text == "none":
        return []
    picked = []
    junk = []
    for part in text.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-", 1)
            try:
                picked.extend(range(int(a), int(b) + 1))
            except ValueError:
                junk.append(part)
        else:
            try:
                picked.append(int(part))
            except ValueError:
                junk.append(part)
    if junk:
        print("  not a number or range: %s" % junk)
        return []
    bad = [p for p in picked if p < 1 or p > n]
    if bad:
        print("  out of range: %s" % bad)
        return []
    return sorted(set(picked))


def interactive_toggle(entries, data):
    """Returns {key: new_value}. Only booleans are offered here."""
    if not entries:
        print("no toggleable boolean keys in scope.")
        return {}
    print_menu(entries)
    intended = {}
    while True:
        try:
            raw = input("select> ")
        except EOFError:
            break
        if raw.strip().lower() == "done":
            break
        if raw.strip().lower() in ("unlock", "u"):
            u = build_unlock(data)
            if not u:
                print("  nothing to unlock - this config is already open.")
                continue
            intended.update(u)
            print("  unlock profile queued: %d keys" % len(u))
            continue
        sel = parse_selection(raw, len(entries))
        if not sel:
            continue
        print()
        for i in sel:
            e = entries[i - 1]
            new = not e["raw"]
            if RICH:
                print("   " + yellow("~") + " " + bold(_ljust(e["key"], 36)) + " "
                      + (green(str(e["raw"])) if e["raw"] else red(str(e["raw"])))
                      + " " + dim("->") + " "
                      + (green(str(new)) if new else red(str(new))))
            else:
                print("   %-38s %s -> %s" % (e["key"], e["raw"], new))
            intended[e["key"]] = new
        print()
        more = input("add more? [y/N] ").strip().lower()
        if more != "y":
            break
    return intended


# --------------------------------------------------------------------------- sec 7

def write_output(data, intended, src_path, out_path, add_missing, reg):
    """sec 7 - write to a new file, then verify. Never in place."""
    out = dict(data)
    added = []
    for k, v in intended.items():
        if k not in out:
            added.append(k)
    out.update(intended)

    out_path = Path(out_path)
    with out_path.open("wb") as fh:
        plistlib.dump(out, fh, fmt=plistlib.FMT_XML)

    return out_path, added


def verify(src, src_path, out_path, intended, add_missing):
    """sec 7 - the five assertions. Returns (ok, errors, stats)."""
    with open(out_path, "rb") as fh:
        produced = plistlib.load(fh)
    errors = []
    src_keys, out_keys = set(src), set(produced)

    # 1 - every intended key changed to the intended value
    for k, v in intended.items():
        if produced.get(k) != v:
            errors.append("A1 intended value not applied: %s expected %r got %r"
                          % (k, v, produced.get(k)))

    # 2 - no other key changed
    for k in sorted(src_keys & out_keys):
        if k not in intended and src[k] != produced[k]:
            errors.append("A2 key changed unexpectedly: %s (%r -> %r)"
                          % (k, src[k], produced[k]))

    # 3 - no key added unless --add-missing
    added = sorted(out_keys - src_keys)
    if added and not add_missing:
        errors.append("A3 keys added without --add-missing: %s" % added)
    removed = sorted(src_keys - out_keys)
    if removed:
        errors.append("A2 keys removed: %s" % removed)

    # 4 - startURL and every non-selected key identical
    if src.get("startURL") != produced.get("startURL"):
        errors.append("A4 startURL changed: %r -> %r"
                      % (src.get("startURL"), produced.get("startURL")))
    for k in sorted(src_keys & out_keys):
        if k not in intended and src[k] != produced[k]:
            errors.append("A4 non-selected key differs: %s" % k)

    stats = {
        "src_bytes": Path(src_path).stat().st_size,
        "out_bytes": out_path.stat().st_size,
        "src_keys": len(src_keys),
        "out_keys": len(out_keys),
        "added": added,
    }
    return (not errors), errors, stats


# --------------------------------------------------------------------------- diff

def diff_configs(a_path, b_path, reg):
    a, _ = detect_and_load(a_path)
    b, _ = detect_and_load(b_path)
    keys = sorted(set(a) | set(b))
    diffs = [(k, a.get(k, "<absent>"), b.get(k, "<absent>")) for k in keys if a.get(k) != b.get(k)]
    if RICH:
        _diff_rich(a_path, b_path, diffs, reg)
    else:
        print("diff: %s  vs  %s" % (a_path, b_path))
        print("  differing keys: %d" % len(diffs))
        for k, va, vb in diffs:
            prop = reg.methods.get(reg.dispatch.get(k, ""), {}).get("prop", "(unmapped)")
            print("    %-34s %-28s -> %-28s  %s" % (k, fmt_raw(va)[:28], fmt_raw(vb)[:28], prop))
    return diffs


# --------------------------------------------------------------------------- main

def parse_set_arg(s, reg):
    if "=" not in s:
        raise SystemExit("--set expects key=value, got %r" % s)
    k, v = s.split("=", 1)
    k, v = k.strip(), v.strip()
    if k in ENUM_SPACES and v in ENUM_SPACES[k]["to"]:
        return k, ENUM_SPACES[k]["to"][v]
    low = v.lower()
    if low == "true":
        return k, True
    if low == "false":
        return k, False
    if low == "allow":
        return k, True
    if low == "block":
        return k, False
    try:
        return k, int(v)
    except ValueError:
        return k, v


def main():
    ap = argparse.ArgumentParser(
        prog="seb_toggle.py",
        description="Scan and toggle Safe Exam Browser .seb config restrictions.")
    ap.add_argument("file", help="input .seb config")
    ap.add_argument("--scan", action="store_true", help="report only, no prompt")
    ap.add_argument("--only-ignored", action="store_true", help="the legacy keys and nothing else")
    ap.add_argument("-c", "--category", help="narrow the toggle menu to one registry category")
    ap.add_argument("-s", "--set", action="append", default=[], metavar="KEY=VALUE",
                    help="non-interactive toggle; repeatable")
    ap.add_argument("-a", "--add-missing", action="store_true",
                    help="allow writing keys the file does not contain")
    ap.add_argument("-y", "--yes", action="store_true", help="skip the confirm prompt")
    ap.add_argument("-o", "--out", help="default: <stem>.modified.seb")
    ap.add_argument("--diff", metavar="OTHER", help="compare two configs and report differing keys")
    ap.add_argument("--unlock-all", action="store_true",
                    help="queue the full relaxation profile (screen capture, keyboard, VM, app blocks, ...)")
    ap.add_argument("--no-color", action="store_true", help="disable ANSI colors")
    args = ap.parse_args()

    if args.no_color:
        set_rich(False)

    reg = Registry(REGISTRY_PATH)
    # allow --only-ignored to work without --scan
    if args.only_ignored:
        args.scan = args.scan or not args.set

    if args.diff:
        diff_configs(args.file, args.diff, reg)
        return 0

    try:
        data, size = detect_and_load(args.file)
    except Refused as exc:
        print("REFUSED: %s" % exc, file=sys.stderr)
        return 2

    src = dict(data)

    rows, absent = scan(data, reg)

    if args.only_ignored:
        ign = [r for r in rows if r["status"] == "IGNORED-BY-3.10.2"]
        if RICH:
            print_ignored_rich(ign)
            return 0
        print("IGNORED-BY-3.10.2: %d keys (macOS / SEB 2.x legacy, not read by 3.10.2)" % len(ign))
        for r in ign:
            print("   %-44s %s" % (r["key"], fmt_raw(r["raw"])))
        return 0

    print_report(data, rows, absent, reg, size, args.file)

    if check_encryption(data):
        print("stopping before the toggle phase: %s = True (sec 3.2)" % ENCRYPTION_KEY)
        return 3

    # resolve intended changes
    intended = {}
    if args.unlock_all:
        intended.update(build_unlock(data))
        print("  RELAXATION PROFILE: %d keys queued" % len(intended))
    for s in args.set:
        k, v = parse_set_arg(s, reg)
        if k not in src and not args.add_missing:
            print("REFUSED: %s is not in the file; pass --add-missing to add it (sec 4.3)" % k, file=sys.stderr)
            return 2
        if k in src and isinstance(src[k], bool) and not isinstance(v, bool):
            print("REFUSED: %s is a boolean; got %r" % (k, v), file=sys.stderr)
            return 2
        intended[k] = v

    entries = build_menu(rows, reg, args.category)

    if not intended and not args.scan:
        intended = interactive_toggle(entries, data)

    if not intended:
        if args.out:
            # sec 9.1 Test A - a no-op round trip still exercises the write path.
            # If this is not byte-identical in content, the writer is lossy.
            out_path = Path(args.out)
            with out_path.open("wb") as fh:
                plistlib.dump(src, fh, fmt=plistlib.FMT_XML)
            ok, errors, stats = verify(src, args.file, out_path, {}, args.add_missing)
            print("WRITE (no-op round trip): %s" % out_path)
            print("  keys %d -> %d" % (stats["src_keys"], stats["out_keys"]))
            if ok:
                print("  VERIFIED: write path is lossless (sec 9.1 Test A)")
                return 0
            print("  ASSERTION FAILURE")
            for e in errors:
                print("    %s" % e)
            return 4
        print("no changes selected. nothing written.")
        return 0

    # sec 6.5 preview
    if RICH:
        print_preview_rich(intended, src)
    else:
        print("PREVIEW DIFF")
        print("-" * 70)
        for k, v in sorted(intended.items()):
            if k in src:
                print("   %-38s %s -> %s" % (k, fmt_raw(src[k]), fmt_raw(v)))
            else:
                print("   %-38s (absent) -> %s        [ADDITION]" % (k, fmt_raw(v)))
        added_preview = [k for k in intended if k not in src]
        if added_preview:
            print("   additions: %s  <- these change the config's identity" % added_preview)

    if not args.yes:
        ans = input("write? [y/N] ").strip().lower()
        if ans != "y":
            print("aborted. nothing written.")
            return 1

    out_path = Path(args.out) if args.out else Path(args.file).with_suffix("").with_name(
        Path(args.file).stem + ".modified.seb")
    if out_path.resolve() == Path(args.file).resolve():
        print("REFUSED: refusing to write in place (sec 7)", file=sys.stderr)
        return 2

    out_path, added = write_output(data, intended, args.file, out_path, args.add_missing, reg)
    ok, errors, stats = verify(src, args.file, out_path, intended, args.add_missing)

    if RICH:
        _write_report_rich(out_path, stats)
    else:
        print()
        print("WRITE: %s" % out_path)
        print("  bytes    : %d -> %d (%+d)" % (stats["src_bytes"] or 0, stats["out_bytes"],
                                               stats["out_bytes"] - (stats["src_bytes"] or 0)))
        print("  keys     : %d -> %d (%+d)" % (stats["src_keys"], stats["out_keys"],
                                               stats["out_keys"] - stats["src_keys"]))
        if stats["added"]:
            print("  added    : %s" % stats["added"])

    if ok:
        print("  VERIFIED: all 5 assertions pass (sec 7)")
        return 0
    print("  ASSERTION FAILURE - deleting output")
    for e in errors:
        print("    %s" % e)
    out_path.unlink(missing_ok=True)
    return 4


if __name__ == "__main__":
    sys.exit(main())
